
version: 2

sources:
  - name: jaffle_shop
    database: raw  
    schema*: jaffle_shop  
    tables:
      - name: orders
      - name: customers

models:
  - name: finance_first_model
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

